
name: Build Astroterm
on: workflow_call

jobs:
  build-all:
    name: Build Astroterm Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.18]
        include:
        - os: darwin
          arch: amd64
        - os: darwin
          arch: arm64
        - os: linux
          arch: 386
        - os: linux
          arch: amd64
        - os: windows
          arch: amd64
          ext: .exe
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      name: Setup Go
      with:
        go-version: ${{ matrix.go_version }}
    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X 'astroterm/version.Version=${{ steps.vars.outputs.tag }}'" -o build/astroterm-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

  save-artifacts:
    name: Upload Build Artifacts
    needs: build-all
    runs-on: ubuntu-latest
    steps:
    - name: List Build Output
      run: ls build