
name: Build Astroterm
on: workflow_call

jobs:
  build-all:
    name: Build Astroterm Binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go_version: [1.18]
        os: [darwin, linux, windows]
        arch: [amd64, arm64]
        include:
          - os: linux
            arch: 386
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      name: Setup Go
      with:
        go-version: ${{ matrix.go_version }}
    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X 'astroterm/version.Version=${{ steps.vars.outputs.tag }}'" -o build/astroterm-${{ matrix.os }}-${{ matrix.arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-binary
        path: |
          build/*