
name: Pull Request
on:
  push

jobs:
  build-binaries:
    uses: matthewp/astroterm/.github/workflows/build.yaml@main

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build-binaries
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: List Binaries
      run: ls build
    - name: Verify Binary Works
      run: build/astroterm-linux-amd64