
name: Pull Request
on:
  push

jobs:
  build-binaries:
    uses: matthewp/astroterm/.github/workflows/build.yaml@main
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build-binaries
    steps:
    - name: Verify Binary Works
    - run: build/astroterm-linux-amd64