# .github/workflows/release.yaml

name: Astroterm Release
on:
  push

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - 1.18
    steps:
    - uses: actions/checkout@v3
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build with xgo
      uses: crazy-max/ghaction-xgo@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        xgo_version: latest
        go_version: ${{ matrix.go_version }}
        dest: build
        targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/arm64,darwin/amd64
        v: true
        x: false
        race: false
        ldflags: -X 'astroterm/version.Version=${{ steps.vars.outputs.tag }}'
    - name: Package artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        ./.github/package.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/**/*