# .github/workflows/release.yaml

name: Astroterm Release
on:
  push

jobs:
  build-binaries:
    name: Build Binaries for Release
    uses: matthewp/astroterm/.github/workflows/build.yaml@main
    if: startsWith(github.ref, 'refs/tags/')

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: build-binaries

    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Package artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        ./.github/package.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/**/*