# .github/workflows/release.yaml

name: Astroterm Release
on:
  push

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - 1.18
    steps:
    - uses: actions/checkout@v3
      with:
        set-safe-directory: '/home/runner/work/astroterm/astroterm'
    - uses: actions/setup-go@v3
      if: startsWith(github.ref, 'refs/tags/')
      name: Setup Go
      with:
        go-version: ${{ matrix.go_version }}
    - name: go version
      if: startsWith(github.ref, 'refs/tags/')
      run: go version
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Adding /source as a safe directory
      run: git config --global --add safe.directory /home/runner/work/astroterm/astroterm
    - name: Build for OSX (amd64)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'astroterm/version.Version=${{ steps.vars.outputs.tag }}'" -o build/astroterm-darwin-amd64
    - name: Build for OSX (arm64)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'astroterm/version.Version=${{ steps.vars.outputs.tag }}'" -o build/astroterm-darwin-arm64
    - name: Build for Linux (386)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        GOOS=linux GOARCH=386 go build -ldflags "-X 'astroterm/version.Version=${{ steps.vars.outputs.tag }}'" -o build/astroterm-linux-386
    - name: Build for Linux (amd64)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags "-X 'astroterm/version.Version=${{ steps.vars.outputs.tag }}'" -o build/astroterm-linux-amd64
    - name: Build for Windows (amd64)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        GOOS=windows GOARCH=amd64 go build -ldflags "-X 'astroterm/version.Version=${{ steps.vars.outputs.tag }}'" -o build/astroterm-windows-amd64.exe
    - name: Package artifacts
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        ./.github/package.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/**/*